const resMessage = {
    pleaseTryAgain: "Somthing went wrong in server please try again",
    wrongAuth: 'Wrong authorization',
    userBlocked: 'Your account has been blocked by support',
    loginSuccess: 'Login successfully',
    logoutSuccess: 'Logout successfully',
    registrationSucc: 'Registration successful',
    dataUpdated: 'Data successfully updated',
    devicetokenUpdated: 'Device token successfully updated',
    userNotFound: "User not found",
    docUpdated: "Document successfully updated",
    fileisrequired: "file is required",
    notificationdeleted: "Notification successfully deleted",
    notificationUpdated: "Notification successfully seen",
    iteneryUpdated: "Itenery successfully updated",
    profileUpdated: "Profile successfully updated",
    noNotification: "No notifications found",
    sosInserted: "SOS data added",
    policeDeleteSucc: 'Police station has been successfully deleted',
    sendNotification: 'Notification successfully sent',
    datainserted: 'Data successfully added',
    dataFound: 'Data Found',
    dataNotFound: 'Data Not Found',
    dataDeleted: 'Data successfully deleted',
    deleteUserAccount: 'User successfully deleted',
    You_are_not_allowed: "You are not allowed to access this page. Please contact admin for grant access",
    userNotExist: "User not found",
    userFound: "User Found",
    incorrectPass: "Incorrect Password",
    updatePassword: 'Password Updated Successfully',
    EmailAlready: 'Email Already Exist',
    dataNotFound: 'Data Not Found',
    linkExpired: 'Oops..! this reset password link has been expired',
    paymentsuccess: 'payment success',
    pendingAccount: 'Your account verification is pending, Please contact to admin.',
    statusChanged: 'status susseccfully changed'
}

module.exports = resMessage